config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: "usages#index", as: :authenticated_root
  end

  unauthenticated do
    root to: 'homes#index'
  end

  namespace :admin do
    resources :carbon_sources, except: [:show, :destroy]
    resources :use_reasons, except: [:show, :destroy]
  end

  resources :carbon_sources, only: [:index, :show]

  resources :usages
end

app/models/carbon_source.rb
class CarbonSource < ActiveRecord::Base
  has_many :usages

  validates :name, presence: true, uniqueness: true
  validates :conversion_factor, presence: true, numericality: {
    greater_than: 0, message: "must be a positive number"
  }
  validates :units, presence: true

  def name_with_units
    "#{name} (#{units})"
  end

  def conversion_units
    if units == "cubic feet"
      "lbs CO2 / cubic foot"
    else
      "lbs CO2 / #{units.chop}"
    end
  end
end

app/models/usage.rb
class Usage < ActiveRecord::Base
  belongs_to :use_reason
  belongs_to :carbon_source
  belongs_to :user

  delegate :conversion_factor, :units, to: :carbon_source

  validates :user, presence: true
  validates :carbon_source, presence: true
  validates :use_reason, presence: true
  validates :amount_used, presence: true, numericality: true
  validates_date :start_date
  validates :start_date, presence: true
  validates_date :end_date, presence: true
  validates :end_date, presence: true

  def number_days
    if start_date == end_date
      1
    else
      (end_date - start_date).to_i + 1
    end
  end

  def display_time_period
    start_date = self.start_date.strftime("%m/%d/%Y")
    end_date = self.end_date.strftime("%m/%d/%Y")
    "#{start_date} - #{end_date}"
  end

  def display_source_info_for_usage
    "#{amount_used} #{units} #{carbon_source.name}"
  end

  def display_emission
    "#{emission.round(2)} lbs CO2"
  end

  def category
    use_reason.name
  end

  def changeable_by?(user)
    user == self.user
  end

  def self.user_usage(user)
    where(user: user).order(end_date: :desc, start_date: :desc)
  end

  def emission
    amount_used * conversion_factor
  end

  def daily_emission
    emission / number_days
  end

  def self.user_total_emissions(user)
    usages = Usage.user_usage(user)
    total_emissions = 0
    usages.each { |usage| total_emissions += usage.emission }
    total_emissions.round(2)
  end

  def self.usages_by_date(user, date)
    Usage.where("user_id = ? AND start_date <= ? AND end_date >= ?",
      user,
      date,
      date)
  end

  def self.total_daily_emissions(user, date)
    usages = Usage.usages_by_date(user, date)
    daily_total = 0
    usages.each { |usage| daily_total += usage.daily_emission }
    daily_total
  end

  def self.daily_emissions_summary(user, start_date, end_date)
    start_date = Date.parse(start_date.to_s)
    end_date = Date.parse(end_date.to_s)
    daily_emissions_hash = { "Type" => "Daily Emissions", "Data" => [] }
    start_date.step(end_date).each do |date|
      daily_emissions_hash["Data"] << {
        "Date" => date.strftime("%m/%d/%Y"),
        "Value" => total_daily_emissions(user, date)
      }
    end
    daily_emissions_hash
  end
end

app/models/use_reason.rb
class UseReason < ActiveRecord::Base
  has_many :usages

  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  ROLES = %w(member admin)

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :role, presence: true, inclusion: {in: ROLES}

  def admin?
    role == 'admin'
  end
end

app/controllers/admin/carbon_sources_controller.rb
module Admin
  class CarbonSourcesController < ApplicationController
    before_action :authenticate_user_is_admin

    def index
      @carbon_sources = CarbonSource.all
      @carbon_source = CarbonSource.new
    end

    def create
      @carbon_source = CarbonSource.new(carbon_source_params)
      if @carbon_source.save
        redirect_to admin_carbon_sources_path,
          notice: "#{@carbon_source.name} added as carbon source"
      else
        @errors = @carbon_source.errors.full_messages
        @carbon_sources = CarbonSource.all
        render :index
      end
    end

    def edit
      @carbon_source = CarbonSource.find(params[:id])
    end

    def update
      @carbon_source = CarbonSource.find(params[:id])
      if @carbon_source.update(carbon_source_params)
        redirect_to admin_carbon_sources_path,
          notice: "#{@carbon_source.name} updated!"
      else
        @errors = @carbon_source.errors.full_messages
        render :edit
      end
    end

    protected

    def carbon_source_params
      params.require(:carbon_source).permit(:name, :conversion_factor,
        :units, :category, :subcategory, :citation, :citation_url)
    end
  end
end

app/controllers/admin/use_reasons_controller.rb
module Admin
  class UseReasonsController < ApplicationController
    before_action :authenticate_user_is_admin

    def index
      @use_reasons = UseReason.all
      @use_reason = UseReason.new
    end

    def create
      @use_reason = UseReason.new(use_reason_params)
      if @use_reason.save
        redirect_to admin_carbon_sources_path,
          notice: "#{@use_reason.name} added as new use reason"
      else
        @errors = @use_reason.errors.full_messages
        @use_reasons = UseReason.all
        render :index
      end
    end

    def edit
      @use_reason = UseReason.find(params[:id])
    end

    def update
      @use_reason = UseReason.find(params[:id])
      if @use_reason.update(use_reason_params)
        redirect_to admin_carbon_sources_path,
          notice: "#{@use_reason.name} updated!"
      else
        @errors = @use_reason.errors.full_messages
        render :edit
      end
    end

    protected

    def use_reason_params
      params.require(:use_reason).permit(:name)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_user_is_admin
    unless current_user.admin?
      redirect_to root_path, alert: "You are not authorized to access that!"
    end
  end

  def after_sign_in_path_for(user)
    usages_path
  end

  def authenticate_user
    unless current_user
      redirect_to root_path, alert: "You are not authorized to access that!"
    end
  end
end

app/controllers/carbon_sources_controller.rb
class CarbonSourcesController < ApplicationController
  def index
    @carbon_sources = CarbonSource.all
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/usages_controller.rb
class UsagesController < ApplicationController
  before_action :authenticate_user

  def index
    if params[:begin_emissions] && params[:end_emissions]
      session[:begin_emissions] = params[:begin_emissions]
      session[:end_emissions] = params[:end_emissions]
    end
    @begin_emissions = session[:begin_emissions] || 30.days.ago
    @end_emissions = session[:end_emissions] || Date.today
    respond_to do |format|
      format.html do
        @usages = Usage.user_usage(current_user).page(params[:page])
        @total_emissions = Usage.user_total_emissions(current_user)
        render :index
      end
      format.json do
        render json: Usage.daily_emissions_summary(
          current_user,
          @begin_emissions,
          @end_emissions
        ).to_json
      end
    end
  end

  def new
    @usage = Usage.new
  end

  def create
    @usage = Usage.new(usage_params)
    @usage.user = current_user
    if @usage.save
      flash[:notice] = "New personal usage added"
      redirect_to usages_path
    else
      @errors = @usage.errors.full_messages
      render :new
    end
  end

  def edit
    @usage = Usage.find(params[:id])
  end

  def update
    @usage = Usage.find(params[:id])
    if @usage.changeable_by?(current_user) && @usage.update(usage_params)
      redirect_to usages_path,
        notice: "Usage updated!"
    else
      @errors = @usage.errors.full_messages
      render :edit
    end
  end

  def destroy
    @usage = Usage.find(params[:id])
    if @usage.changeable_by?(current_user)
      @usage.destroy
      flash[:notice] = "Usage deleted"
      redirect_to usages_path
    end
  end

  protected

  def usage_params
    params.require(:usage).permit(:carbon_source_id, :amount_used, :units,
      :start_date, :end_date, :notes, :use_reason_id)
  end
end

app/views/admin/carbon_sources/_new.html.haml
= form_for [:admin, @carbon_source] do |f| 
  .row
    .small-12.columns
      = f.label :name
      = f.text_field :name

  .row
    .small-6.columns
      = f.label :conversion_factor
      = f.text_field :conversion_factor

    .small-6.columns
      = f.label :units
      = f.text_field :units

  .row
    .small-12.columns
      = f.label :citation
      = f.text_field :citation

    .small-12.columns
      = f.label :citation_url, "Citation URL"
      = f.text_field :citation_url, placeholder: "http://"

  .row
    .small-12.columns
      = f.submit "Add new source", class: "button secondary"

app/views/admin/carbon_sources/edit.html.haml
= render 'shared/errors' if @errors

.row
  .small-12.columns
    %h2 Edit Carbon Source

= form_for [:admin, @carbon_source] do |f|
  .row
    .small-12.columns
      = f.label :name
      = f.text_field :name

  .row
    .small-6.columns
      = f.label :conversion_factor
      = f.text_field :conversion_factor

    .small-6.columns
      = f.label :units
      = f.text_field :units

  .row
    .small-12.columns
      = f.submit "Edit source", class: "button secondary"

app/views/admin/carbon_sources/index.html.haml
= render 'shared/errors' if @errors

.row
  .small-4.columns
    %h2 Add New Carbon Source
    = render 'new'

  .small-8.columns
    %h2 All Sources
    - if @carbon_sources 
      - @carbon_sources.each do |carbon_source|
        .panel
          %h3= carbon_source.name
          %h5 Conversion:
          %span.subheader
            = "#{carbon_source.conversion_factor} #{carbon_source.conversion_units}"
          %h5 Source:
          %span.subheader
            = link_to "#{carbon_source.citation}", carbon_source.citation_url, target: "_blank"
          %h6
          %small= link_to "Edit #{carbon_source.name}", edit_admin_carbon_source_path(carbon_source)

app/views/admin/carbon_sources/new.html.erb
<%= form_for [:admin, @carbon_source] do |f| %>
  <%= f.label :source %>
  <%= f.text_field :source %>

  <%= f.label :conversion_factor %>
  <%= f.text_field :conversion_factor %>

  <%= f.label :conversion_units %>
  <%= f.text_field :conversion_units %>

  <%= f.label :category %>
  <%= f.select :category,
      CarbonSource::CATEGORIES,
      :include_blank => "Please Choose A Category" %>

  <%= f.label :subcategory %>
  <%= f.select :subcategory,
      CarbonSource::SUBCATEGORIES,
      :include_blank => "Please Choose A Subcategory" %>

  <%= f.submit "Add new source"  %>
<% end %>

app/views/admin/use_reasons/_new.html.haml
= form_for [:admin, @use_reason] do |f|
  .row
    .small-12.columns
      = f.label :name
      = f.text_field :name

      = f.submit "Add new reason", class: "button secondary"

app/views/admin/use_reasons/edit.html.haml
= render 'shared/errors' if @errors

%h2 Edit Use Reason

= form_for [:admin, @use_reason] do |f|
  = f.label :name
  = f.text_field :name

  = f.submit "Edit Reason"

app/views/admin/use_reasons/index.html.haml
= render 'shared/errors' if @errors

.row
  .small-4.columns
    %h2 Add New Use Reason
    = render 'new'

  .small-8.columns
    %h2 Use Reasons
    - if @use_reasons
      - @use_reasons.each do |reason|
        .panel
          %h3= reason.name
          %h6
          %small= link_to "Edit #{reason.name}", edit_admin_use_reason_path(reason)

app/views/carbon_sources/index.html.haml
.row
  .small-12.text-center.columns
    %h2 All Sources

.row
  .small-8.small-centered.columns
    - if @carbon_sources
      - @carbon_sources.each do |carbon_source|
        .panel
          %h3= carbon_source.name
          %h5 Conversion:
          %span.subheader
            = "#{carbon_source.conversion_factor} #{carbon_source.conversion_units}"

          %h5 Source:
          %span.subheader
            = link_to carbon_source.citation, carbon_source.citation_url, target: "_blank"

app/views/homes/index.html.haml
= render 'shared/errors' if @errors

.row
  .small-8.small-centered.columns
    = image_tag "grassandtree.jpg", alt:"Pretty outside image"
    %hr

.row
  .small-4.columns
    %h4 What are emissions?
    %p 
      Carbon emission refers to the carbon dioxide that is released into the 
      atmosphere when fossil fuels are burned. Fossil fuels with higher 
      carbon content will have higher emissions. Carbon emissions are a driver 
      of climate change.
    %hr

    %h4 Want to learn more?
    %ul
      %li= link_to "EPA information on emissions",
        "http://www.epa.gov/climatechange/ghgemissions/",
        target: "_blank"
      %li= link_to "What is a carbon footprint?",
        "http://en.wikipedia.org/wiki/Carbon_footprint",
        target: "_blank"

  .small-4.columns
    %h4 Why track?
    %p 
      Tracking your personal emissions (your carbon footprint) can give you insight 
      into how your actions may have an impact on the environment. There are two kinds 
      of emissions to track: direct and indirect.
    
    %p
      %em Direct emissions 
      are emissions created by sources you own or control. For an individual, 
      this would be your car or heating your house.
    
    %p
      %em Indirect emissions
      are emissions created by someone else on your behalf. Emissions that 
      would fall into this are the emissions created by electricity 
      generation or the production of goods made. For the purposes of tracking 
      here, we consider emissions related to the purchase of electricity.

  .small-4.columns
    %h4 What's Your Footprint
    %h5= link_to "What we track", carbon_sources_path
    %p
      Once you are registered, you can enter your usage for the different sources
      of emissions you are responsible for. Information can come from your electric,
      gas, or oil bills. Information will also come from how much gas you use in your
      car.
    %p
      When you have new information, log in and click on new personal usage. That's
      where you enter your energy usage. Those emissions will be added to your personal
      total!
  %hr

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title CarbonFootprint
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags 

  %body

    %nav.top-bar{"data-topbar"=> "", "role"=> "navigation"}
      %ul.title-area
        %li.name
          %h1= link_to "What's Your Footprint?", root_path

      %section.top-bar-section
        %ul.right
          %li.has-dropdown
            - if current_user.try(:admin?)
              %a{href: "#"} Admin
              %ul.dropdown
                %li= link_to "Carbon Sources", admin_carbon_sources_path
                %li= link_to "Use Reasons", admin_use_reasons_path
          - if current_user
            %li= link_to 'Sign Out', destroy_user_session_path, method: :delete
          - else
            %li= link_to 'Sign Up', new_user_registration_path
            %li= link_to 'Sign In', new_user_session_path

    - flash.each do |key, value|
      %div.alert-box.secondary{"data-alert"=> ""}
        = value

    = yield

    = javascript_include_tag 'application'
    = yield :extra_footer

app/views/shared/_errors.html.erb
<div data-alert="" class="alert-box alert">
  <ul>
    <% @errors.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
</div>

app/views/usages/edit.html.haml
= render "shared/errors" if @errors

%h2 Edit Usage
= form_for @usage do |f|
  .row
    .small-12.columns
      = f.label :carbon_source_id, "Source"
      = f.collection_select(:carbon_source_id,
        CarbonSource.all, :id, :name_with_units,
        include_blank: "Please choose a source")

  .row
    .small-6.columns
      = f.label :amount_used
      = f.text_field :amount_used

    .small-6.columns
      = f.label :use_reason_id, "Use reason"
      = f.collection_select(:use_reason_id,
        UseReason.all, :id, :name,
        include_blank: "Please choose a use reason")

  .row
    .small-6.columns
      = f.label :start_date
      = f.text_field :start_date

    .small-6.columns
      = f.label :end_date
      = f.text_field :end_date

  .row
    .small-12.columns
      = f.label :notes
      = f.text_area :notes

  .row
    .small-12.columns
      = f.submit "Edit usage", class: "button secondary"

app/views/usages/index.html.haml
= rendor "share/errors" if @errors

.row
  .small-12.columns
    %h1.text-center.footprint-header Your Carbon Footprint

.row
  .small-4.columns
    .row
      .small-12.text-center.columns
        = link_to "Add personal usage", new_usage_path, class: "button info"

    .row
      .small-12.columns
        %h3.text-center Entry Overview
        - if @usages
          %ul.accordion{"data-accordion"=> ""}
            - @usages.each do |usage|
              %li.accordion-navigation
                = link_to "#panel_#{usage.id}", title: "Usage for time period" do
                  %h5= "#{usage.display_time_period}:"
                  %h5.subheader= usage.display_emission
                %div.content#panel{id: usage.id}
                  %h5 
                    Source Info: 
                    %span.subheader= usage.display_source_info_for_usage 
                  %h5
                    Use Reason: 
                    %span.subheader= usage.category
                  %h5
                    Notes: 
                    %span.subheader= usage.notes
                  %h6
                  %small
                    = link_to "Edit this entry", edit_usage_path(usage)
                    = link_to "Delete this entry", usage_path(usage), method: :delete, data: { confirm: "Are you sure you want to delete?" }
        .row
          .small-12.text-center.columns
            = paginate @usages
    .row
      .small-12.text-center.columns.sources-link
        = link_to "Sources to track", carbon_sources_path

  .small-8.columns
    .row
      .small-12.columns
        %h2 Total Emissions:
        %h3.subheader= "#{@total_emissions} lbs CO2"
        %hr

    .row
      .small-12.columns
        #chart
          = form_tag usages_path, method: :get do
            .row
              .small-4.columns
                = label_tag :begin_emissions
                = text_field_tag :begin_emissions

              .small-4.columns
                = label_tag :end_emissions
                = text_field_tag :end_emissions

              .small-4.columns
                = submit_tag "Enter Time Frame", class: "button small success"

app/views/usages/new.html.haml
= render "shared/errors" if @errors

= form_for @usage do |f|
  .row
    .small-12.columns
      = f.label :carbon_source_id, "Source"
      = f.collection_select(:carbon_source_id,
        CarbonSource.all, :id, :name_with_units,
        prompt: "Please choose a source")

  .row
    .small-6.columns
      = f.label :amount_used
      = f.text_field :amount_used

    .small-6.columns
      = f.label :use_reason_id, "Use reason"
      = f.collection_select(:use_reason_id,
        UseReason.all, :id, :name,
        prompt: "Please choose a use reason")

  .row
    .small-6.columns
      = f.label :start_date
      = f.text_field :start_date

    .small-6.columns
      = f.label :end_date
      = f.text_field :end_date

  .row
    .small-12.columns
      = f.label :notes
      = f.text_area :notes

  .row
    .small-12.columns
      = f.submit "Add new usage", class: "button secondary"